### ISSUE TITLE
Application consistently fails to reload

### ISSUE THREAD

**Issue by jacobEwing** [maxwellito/minimator#4]
Minimator worked well the first time I used it in Brave (Chromium spinoff), but after closing it and reloading the page, it now gets stuck on the "Please wait, it's loading" screen.

Checking the developer console, this seems to be caused by issues loading client side data:

storage.js:36 Uncaught Error: Couldn't retrieve the item 1 from LocalStorage.
    at Storage.getItem (storage.js:36)
    at new HomeCardComponent (home-card.cmp.js:65)
    at home.cmp.js:37
    at Array.forEach (<anonymous>)
    at new HomeComponent (home.cmp.js:36)
    at Router.appRouter.onChange (main.js:44)
    at Router.hashChange (router.js:35)
    at main.js:57

If I switch the browser to incognito mode it works fine, if I switch to another browser it works fine.

**Comment by maxwellito** [comment]
I'm afraid Brave has some security or fingerprinting mecanism which is messing up with the app by blocking access to the LocalStorage. I'm completely powerless in this situation, it's a user setting to change in your browser.
